#!/bin/bash

rm         .classpath
rm         .project
rm       */.classpath
rm       */.project
rm     */*/.classpath
rm     */*/.project
rm   */*/*/.classpath
rm   */*/*/.project
rm */*/*/*/.classpath
rm */*/*/*/.project
mvn eclipse:eclipse  -DdownloadSources=true

echo done



